language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt

env:
  -CODECOV_TOKEN="5d6ae089-b1e9-4210-a224-e67c896fb60f"
# command to run tests
script:
  - pytest --cov-report term --cov=src/
after_success:
  - codecov
